# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - kwazi-portfolio

on:
  push:
    branches:
      - port
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest # Using ubuntu for consistency and command compatibility

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
      
      - name: Remove node_modules before artifact upload
        run: rm -rf node_modules

      - name: Zip artifact for deployment
        run: zip -r deployment.zip . 

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: deployment.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9E5583A4F1774762A061657A1E6E7DE4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B0FBDF4CA75F415B9492169EC61D4545 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8F33BE82EE41451FBE622BA7858D7055 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'kwazi-portfolio'
          slot-name: 'Production'
          package: 'deployment.zip'
